Retails Analysis
--------------------------Table Creation------------------

CREATE DATABASE RETAILS;
USE RETAILS;
USE SCHEMA RETAILS.PUBLIC;

--------------------CREATE TABLES--------------------

CREATE OR REPLACE TABLE demographic_RAW
(AGE_DESC	CHAR(20),
MARITAL_STATUS_CODE	CHAR(5),
INCOME_DESC	VARCHAR(40),
HOMEOWNER_DESC	VARCHAR(40),
HH_COMP_DESC	VARCHAR(50),
HOUSEHOLD_SIZE_DESC	VARCHAR(50),
KID_CATEGORY_DESC	VARCHAR(40),
household_key INT PRIMARY KEY
);

CREATE OR REPLACE TABLE CAMPAIGN_DESC_RAW
(DESCRIPTION CHAR(10),	
CAMPAIGN	INT ,
START_DAY	INT,
END_DAY INT,
PRIMARY KEY (DESCRIPTION),
UNIQUE (CAMPAIGN));




CREATE OR REPLACE TABLE CAMPAIGN_RAW
(DESCRIPTION	CHAR(10) ,
household_key	INT,
CAMPAIGN INT,
FOREIGN KEY (DESCRIPTION) references CAMPAIGN_DESC_RAW(DESCRIPTION) ,
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN),
FOREIGN KEY (household_key) references demographic_RAW(household_key)
);

CREATE OR REPLACE TABLE PRODUCT_RAW
(PRODUCT_ID	INT PRIMARY KEY,
MANUFACTURER 	INT,
DEPARTMENT	VARCHAR(50),
BRAND	VARCHAR(30),
COMMODITY_DESC	VARCHAR(65),
SUB_COMMODITY_DESC VARCHAR(65)	,
CURR_SIZE_OF_PRODUCT VARCHAR(15)
);


CREATE OR REPLACE TABLE COUPON_RAW
(COUPON_UPC	INT,
PRODUCT_ID	INT,
CAMPAIGN INT,
FOREIGN KEY (PRODUCT_ID) references PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN)
);


CREATE OR REPLACE TABLE COUPON_REDEMPT_RAW
(household_key	INT,
DAY	INT,
COUPON_UPC	INT,
CAMPAIGN INT,
FOREIGN KEY (household_key) references demographic_RAW(household_key),
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN)
);

CREATE OR REPLACE TABLE TRANSACTION_RAW 
(household_key	INT,
BASKET_ID	INT,
DAY	INT,
PRODUCT_ID	INT,
QUANTITY	INT,
SALES_VALUE	FLOAT,
STORE_ID	INT,
RETAIL_DISC	FLOAT,
TRANS_TIME	INT,
WEEK_NO	INT,
COUPON_DISC	INT,
COUPON_MATCH_DISC INT,
FOREIGN KEY (PRODUCT_ID) references PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (household_key) references demographic_RAW(household_key)
);

--------------------------------------------------------------------------------
--------------------------------Storage Integration-----------------------------

USE RETAILS;

--CREATE STORAGE INTEGRATION
CREATE OR REPLACE STORAGE integration s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::347301642642:role/RETAIL_ROLE'
STORAGE_ALLOWED_LOCATIONS =('s3://hhretail-bucket/');

DESC STORAGE integration s3_int;

--CREATE FILE FORMAT
create or replace file format RETAIL_CSV 
    type = 'csv' 
    compression = 'none' 
    field_delimiter = ','
    field_optionally_enclosed_by = 'none'
    skip_header = 1 ;

--CREATE STAGE
CREATE OR REPLACE STAGE RETAIL_STAGE
URL = 's3://hhretail-bucket'
file_format = RETAIL_CSV
storage_integration = s3_int;

LIST @RETAIL_STAGE;
SHOW STAGES;

------------------------------------------------------------------------------
----------------------------PipeLine----------Stored Procedure------Tasks--------------------------

--CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE

--The AUTO_INGEST=true parameter specifies to read 
--- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.
USE RETAILS;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.DEMOGRAPHIC_RAW            --yourdatabase -- your schema ---your table
FROM '@RETAIL_STAGE/DEMOGRAPHIC/' --s3 bucket subfolde4r name (@RETAIL_STAGE IS STAGE NAME (MEANS SOMEONE IS AT YOUR DOOR))
FILE_FORMAT = RETAIL_CSV;                           --YOUR CSV FILE FORMAT NAME

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN_DESC AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.CAMPAIGN_DESC_RAW
FROM '@RETAIL_STAGE/CAMPAIGN_DESC/' 
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.CAMPAIGN_RAW
FROM '@RETAIL_STAGE/CAMPAIGN/' 
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_PRODUCT AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.PRODUCT_RAW
FROM '@RETAIL_STAGE/PRODUCT/' 
FILE_FORMAT = RETAIL_CSV;


CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.COUPON_RAW
FROM '@RETAIL_STAGE/COUPON/' 
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON_REDEMPT  AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.COUPON_REDEMPT_RAW
FROM '@RETAIL_STAGE/COUPON_REDEMPT/' 
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_TRANSACTION  AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.TRANSACTION_RAW
FROM '@RETAIL_STAGE/TRANSACTION/' 
FILE_FORMAT = RETAIL_CSV;

SHOW PIPES;

SELECT COUNT(*) FROM demographic_RAW;
SELECT COUNT(*) FROM CAMPAIGN_DESC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_RAW;
SELECT COUNT(*) FROM PRODUCT_RAW;
SELECT COUNT(*) FROM COUPON_RAW;
SELECT COUNT(*) FROM COUPON_REDEMPT_RAW;
SELECT COUNT(*) FROM TRANSACTION_RAW;

----------------------------------------------------------PIPEREFRESH-----------------------------------------------------------------

ALTER PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC refresh;
ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN_DESC refresh;
ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN refresh;
ALTER PIPE  RETAIL_SNOWPIPE_PRODUCT refresh;
ALTER PIPE  RETAIL_SNOWPIPE_COUPON refresh;
ALTER PIPE  RETAIL_SNOWPIPE_COUPON_REDEMPT refresh;
ALTER PIPE  RETAIL_SNOWPIPE_TRANSACTION refresh;



SELECT * FROM demographic_RAW;
SELECT * FROM CAMPAIGN_DESC_RAW;
SELECT * FROM CAMPAIGN_RAW;
SELECT * FROM PRODUCT_RAW;
SELECT * FROM COUPON_RAW;
SELECT * FROM COUPON_REDEMPT_RAW;
SELECT * FROM TRANSACTION_RAW;

------CREATING PROCEDURES FOR PIPE-------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC REFRESH';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_DEMOGRAPHIC refreshed successfully.';
END;
$$;
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN_DESC refresh';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_CAMPAIGN_DES successfully.';
END;
$$;
------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_CAMPAIGN_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_CAMPAIGN refresh;';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_CAMPAIGN successfully.';
END;
$$;
-------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_PRODUCT_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_PRODUCT refresh;';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_PRODUCT successfully.';
END;
$$;
-------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_COUPON_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_COUPON refresh;';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_COUPON successfully.';
END;
$$;
-------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_COUPON_REDEMPT refresh;';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_COUPON_REDEMPT successfully.';
END;
$$;
-------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RETAIL_SNOWPIPE_TRANSACTION_REFRESH()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  EXECUTE IMMEDIATE 'ALTER PIPE  RETAIL_SNOWPIPE_TRANSACTION refresh;';
  
  RETURN 'Pipe RETAIL_SNOWPIPE_TRANSACTION successfully.';
END;
$$;

SHOW PROCEDURES;

CALL RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH();
CALL RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH();
CALL RETAIL_SNOWPIPE_PRODUCT_REFRESH();
CALL RETAIL_SNOWPIPE_CAMPAIGN_REFRESH();
CALL RETAIL_SNOWPIPE_COUPON_REFRESH();
CALL RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH();
CALL RETAIL_SNOWPIPE_TRANSACTION_REFRESH();

------CREATING TASK------------------
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC' 
AS CALL RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH();
-----
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC'
AS CALL RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH();
-----
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_PRODUCT_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC' 
AS CALL RETAIL_SNOWPIPE_PRODUCT_REFRESH();
------
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_CAMPAIGN_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC' 
AS CALL RETAIL_SNOWPIPE_CAMPAIGN_REFRESH();
------
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_COUPON_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC' 
AS CALL RETAIL_SNOWPIPE_COUPON_REFRESH();
------
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 18 * * 6 UTC' 
AS CALL RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH();
------
CREATE OR REPLACE TASK  RETAIL_SNOWPIPE_TRANSACTION_REFRESH_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 10 14 * * 0 UTC' 
AS CALL RETAIL_SNOWPIPE_TRANSACTION_REFRESH();

SHOW TASKS;

ALTER TASK   RETAIL_SNOWPIPE_TRANSACTION_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_TRANSACTION_REFRESH_TASK SUSPEND; 

ALTER TASK   RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_DEMOGRAPHIC_PIPE_REFRESH_TASK SUSPEND;

ALTER TASK   RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_CAMPAIGN_DESC_REFRESH_TASK SUSPEND;

ALTER TASK   RETAIL_SNOWPIPE_PRODUCT_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_PRODUCT_REFRESH_TASK SUSPEND;

ALTER TASK   RETAIL_SNOWPIPE_CAMPAIGN_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_CAMPAIGN_REFRESH_TASK SUSPEND;

ALTER TASK   RETAIL_SNOWPIPE_COUPON_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_COUPON_REFRESH_TASK SUSPEND;

ALTER TASK   RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH_TASK RESUME;
ALTER TASK  RETAIL_SNOWPIPE_COUPON_REDEMPT_REFRESH_TASK SUSPEND;




-----------------------------------------------------------------------------------
----------------------------------------Query---------------------------------------
USE RETAILS;

SELECT * FROM RETAILS.PUBLIC.PRODUCT_RAW;
---- department wise product------
SELECT DEPARTMENT, COUNT(PRODUCT_ID)
FROM RETAILS.PUBLIC.PRODUCT_RAW
GROUP BY DEPARTMENT;

SELECT CURRENT_USER();
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();

SELECT *FROM RETAILS.PUBLIC.CAMPAIGN_DESC_NEW;

SELECT * FROM RETAILS.PUBLIC.COUPON_REDEMPT_NEW;

SELECT * FROM RETAILS.PUBLIC.TRANSACTION_NEW;

SELECT *FROM RETAILS.PUBLIC.TRANSACTION_RAW;

SELECT * FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW;

/*1. Customer Demographics KPIs: 
A) Count of unique households: Measure the total number of unique households in 
the Demographic table.*/

SELECT COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW;

/* B) Household composition distribution: Analyze the distribution of household 
compositions (HH_COMP_DESC) to understand the composition of households. */

SELECT HH_COMP_DESC, COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1
ORDER BY 2 DESC;

/*C) Age distribution: Calculate the percentage or count of customers in different age 
groups (AGE_DESC).*/

SELECT AGE_DESC,TOTAL_HOUSEHOLDS,ROUND(TOTAL_HOUSEHOLDS/2500 * 100,2) AS PERC_AGEWISE_HOUSEHOLDS_DIST
FROM (
SELECT AGE_DESC, COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1
ORDER BY 2 DESC
)
GROUP BY 1,2;

/*D) Marital status distribution: Analyze the proportion of customers in different 
marital status categories (MARITAL_STATUS_CODE). */

SELECT MARITAL_STATUS_CODE, COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS,
ROUND(COUNT(DISTINCT HOUSEHOLD_KEY)/2500 * 100,2) AS PERC_MARITAL_HOUSEHOLD_DIST
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1
ORDER BY 2 DESC;


/*E) Income distribution: Determine the distribution of customers across income levels 
(INCOME_DESC).*/

SELECT INCOME_DESC,COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS,
ROUND(COUNT(DISTINCT HOUSEHOLD_KEY)/2500 * 100,2)
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1
ORDER BY 2;


/*F) Homeownership distribution: Calculate the percentage or count of customers who 
own or rent their homes (HOMEOWNER_DESC).*/

SELECT HOMEOWNER_DESC , 
COUNT(DISTINCT HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS,
ROUND(COUNT(DISTINCT HOUSEHOLD_KEY) / 2500 * 100 , 2) AS PERC_HOMEOWNER_DESC_DISTR
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1
ORDER BY 2 DESC;

-----------Stored Procedure------kpi----
CREATE OR REPLACE PROCEDURE TRANSACTION_RAW()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE TRANSACTION_RAW AS (SELECT * FROM RETAILS.PUBLIC.TRANSACTION_RAW);
$$;

SHOW PROCEDURES;

CALL TRANSACTION_RAW();

CREATE OR REPLACE TASK  TRANSACTION_RAW_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 14 * * 0 UTC' 
AS CALL TRANSACTION_RAW();

SHOW TASKS;

ALTER TASK   TRANSACTION_RAW_TASK RESUME;
ALTER TASK  TRANSACTION_RAW_TASK SUSPEND; 

SELECT * FROM  ;

---------------------------------------------------------------------------------------

SELECT T.HOUSEHOLD_KEY,D.AGE_DESC,D.MARITAL_STATUS_CODE,D.INCOME_DESC,AVG(T.SALES_VALUE)AS AVG_AMOUNT,
AVG(T.RETAIL_DISC)AS AVG_RETAIL_DIS,AVG(T.COUPON_DISC)AS AVG_COUPON_DISC,AVG(T.COUPON_MATCH_DISC)AS AVG_COUP_MATCH_DISC
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
LEFT OUTER JOIN RETAILS.PUBLIC.DEMOGRAPHIC_RAW D ON T.HOUSEHOLD_KEY =D.HOUSEHOLD_KEY
GROUP BY 1,2,3,4
ORDER BY 1;
-----------
CREATE OR REPLACE PROCEDURE Household_Kpi()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE Household_Kpi AS (SELECT T.HOUSEHOLD_KEY,D.AGE_DESC,D.MARITAL_STATUS_CODE,D.INCOME_DESC,AVG(T.SALES_VALUE)AS AVG_AMOUNT,
AVG(T.RETAIL_DISC)AS AVG_RETAIL_DIS,AVG(T.COUPON_DISC)AS AVG_COUPON_DISC,AVG(T.COUPON_MATCH_DISC)AS AVG_COUP_MATCH_DISC
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
LEFT OUTER JOIN RETAILS.PUBLIC.DEMOGRAPHIC_RAW D ON T.HOUSEHOLD_KEY =D.HOUSEHOLD_KEY
GROUP BY 1,2,3,4
ORDER BY 1);
$$;

SHOW PROCEDURES;

CALL Household_kpi();

CREATE OR REPLACE TASK  Household_kpi_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 30 20 * * 6 UTC' 
AS CALL Household_kpi();

SHOW TASKS;

ALTER TASK   Household_kpi_TASK RESUME;
ALTER TASK  Household_kpi_TASK SUSPEND; 

SELECT * FROM  RETAILS.PUBLIC.HOUSEHOLD_KPI;

---------------------------------------------------
/*2. Campaign KPIs: 
o A) Number of campaigns: Count the total number of campaigns in the Campaign 
table. */

SELECT * FROM RETAILS.PUBLIC.CAMPAIGN_DESC_RAW;

SELECT COUNT(CAMPAIGN) AS TOTAL_CAMPAING FROM RETAILS.PUBLIC.CAMPAIGN_DESC_RAW;


/*o B) Campaign duration: Calculate the duration of each campaign by subtracting the 
start day from the end day (in the Campaign_desc table). */

SELECT CAMPAIGN, (END_DAY-START_DAY) AS CAMPAIGN_DURATION FROM RETAILS.PUBLIC.CAMPAIGN_DESC_RAW;

/*o C) Campaign effectiveness: Analyze the number of households associated with each 
campaign (in the Campaign table) to measure campaign reach. */

SELECT COUNT(DISTINCT HOUSEHOLD_KEY) FROM RETAILS.PUBLIC.CAMPAIGN_RAW;

SELECT HOUSEHOLD_KEY, COUNT(CAMPAIGN) FROM RETAILS.PUBLIC.CAMPAIGN_RAW
GROUP BY 1
ORDER BY 2 DESC;


SELECT T.HOUSEHOLD_KEY,CR.CAMPAIGN,AVG(T.SALES_VALUE)AS AVG_AMOUNT,
AVG(T.RETAIL_DISC)AS AVG_RETAIL_DIS,AVG(T.COUPON_DISC)AS AVG_COUPON_DISC,AVG(T.COUPON_MATCH_DISC)AS AVG_COUP_MATCH_DISC
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
LEFT OUTER JOIN RETAILS.PUBLIC.CAMPAIGN_RAW CR
ON T.HOUSEHOLD_KEY=CR.HOUSEHOLD_KEY
GROUP BY 1,2
ORDER BY 1;
-----------------------------------------
CREATE OR REPLACE PROCEDURE CAMPAIGN_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE CAMPAIGN_KPI AS (SELECT T.HOUSEHOLD_KEY,CR.CAMPAIGN,AVG(T.SALES_VALUE)AS AVG_AMOUNT,
AVG(T.RETAIL_DISC)AS AVG_RETAIL_DIS,AVG(T.COUPON_DISC)AS AVG_COUPON_DISC,AVG(T.COUPON_MATCH_DISC)AS AVG_COUP_MATCH_DISC
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
LEFT OUTER JOIN RETAILS.PUBLIC.CAMPAIGN_RAW CR
ON T.HOUSEHOLD_KEY=CR.HOUSEHOLD_KEY
GROUP BY 1,2
ORDER BY 1);
$$;

SHOW PROCEDURES;

CALL CAMPAIGN_KPI();

CREATE OR REPLACE TASK CAMPAIGN_KPI_TASK
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL CAMPAIGN_KPI();

SHOW TASKS;

ALTER TASK CAMPAIGN_KPI_TASK RESUME;
ALTER TASK CAMPAIGN_KPI_TASK SUSPEND;

SELECT * FROM RETAILS.PUBLIC.CAMPAIGN_KPI;
------------------------------------------------------------------------------------------------
/*3. Coupon KPIs: 
o A) Coupon redemption rate: Calculate the percentage of coupons redeemed (from the 
coupon_redempt table) compared to the total number of coupons distributed (from 
the Coupon table). */
CREATE OR REPLACE PROCEDURE PCT_COUPON_REDEEM_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE PCT_COUPON_REDEEM_KPI AS (SELECT 
    CR.CAMPAIGN,
    COUNT(DISTINCT CRN.COUPON_UPC) AS Unique_Redeemed,
    COUNT(DISTINCT CR.COUPON_UPC) AS Total_Issued,
    ROUND(
        (COUNT(DISTINCT CRN.COUPON_UPC) * 100.0) / 
        (COUNT(DISTINCT CR.COUPON_UPC)), 
    2) AS REDEMPTION_RATE_PCT
FROM RETAILS.PUBLIC.COUPON_RAW CR
LEFT JOIN RETAILS.PUBLIC.COUPON_REDEMPT_NEW CRN 
    ON CR.CAMPAIGN = CRN.CAMPAIGN
GROUP BY CR.CAMPAIGN
ORDER BY REDEMPTION_RATE_PCT DESC);
$$;
CALL PCT_COUPON_REDEEM_KPI();
/*
o B) Coupon usage by campaign: Measure the number of coupon redemptions (from 
the coupon_redempt table) for each campaign (in the Coupon table). */

CREATE OR REPLACE PROCEDURE UNIQUE_COUPON_REDEMTION_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE UNIQUE_COUPON_REDEMTION_KPI AS (SELECT CR.CAMPAIGN, COUNT(CRN.COUPON_UPC) AS TOTAL_REDEMPTION,
COUNT(DISTINCT CRN.COUPON_UPC) AS UNIQUE_COUPONS_REDEEMED FROM
RETAILS.PUBLIC.COUPON_RAW CR
LEFT JOIN RETAILS.PUBLIC.COUPON_REDEMPT_NEW CRN
ON CR.CAMPAIGN=CRN.CAMPAIGN
GROUP BY 1 
ORDER BY 2);
$$;

CALL UNIQUE_COUPON_REDEMTION_KPI();
------------------------------------------------------------------------------------
/*4. Product KPIs: 
o A)Sales value: Calculate the total sales value for each product (in the 
Transaction_data table) to identify top-selling products. */
CREATE OR REPLACE PROCEDURE TOP_SELLING_PRODUCT()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE TOP_SELLING_PRODUCT AS (SELECT T.PRODUCT_ID, P.COMMODITY_DESC,SUM(T.SALES_VALUE) AS TOTAL_AMOUNT
FROM RETAILS.PUBLIC.TRANSACTION_NEW T 
LEFT JOIN RETAILS.PUBLIC.PRODUCT_RAW P
ON T.PRODUCT_ID=P.PRODUCT_ID
GROUP BY 1,2
ORDER BY 3 DESC);
$$;

CALL TOP_SELLING_PRODUCT();
SHOW PROCEDURES;

CREATE OR REPLACE TASK TOP_SELLING_PRODUCT
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL TOP_SELLING_PRODUCT();

SHOW TASKS;

ALTER TASK TOP_SELLING_PRODUCT RESUME;
ALTER TASK TOP_SELLING_PRODUCT SUSPEND;

SELECT * FROM RETAILS.PUBLIC.TOP_SELLING_PRODUCT;

/*oB) Manufacturer distribution: Analyze the distribution of products across different 
manufacturers (in the Product table). */

CREATE OR REPLACE PROCEDURE PCT_SHARE_INVENTORY()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE PCT_SHARE_INVENTORY AS (SELECT MANUFACTURER,COUNT(PRODUCT_ID) AS TOTAL_PRODUCT,
COUNT(DISTINCT COMMODITY_DESC) AS CATEGORY,
ROUND(COUNT(PRODUCT_ID)*100/SUM(COUNT(PRODUCT_ID)) OVER(),2) AS PCT_SHARE_INVENTORY
FROM RETAILS.PUBLIC.PRODUCT_RAW
GROUP BY 1
ORDER BY 2 DESC);
$$;

CALL PCT_SHARE_INVENTORY();
SELECT * FROM RETAILS.PUBLIC.PCT_SHARE_INVENTORY;
/*oC) Department-wise sales: Measure the sales value by department (in the Product 
table) to understand which departments contribute most to revenue. */

CREATE OR REPLACE PROCEDURE DEPARTMENT_WISE_SALES_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE DEPARTMENT_WISE_SALES_KPI AS
(SELECT P.DEPARTMENT,SUM(T.SALES_VALUE) AS TOTAL_AMOUNT 
FROM RETAILS.PUBLIC.PRODUCT_RAW P
LEFT JOIN RETAILS.PUBLIC.TRANSACTION_NEW T
ON P.PRODUCT_ID=T.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC);
$$;

CALL DEPARTMENT_WISE_SALES_KPI();

SHOW PROCEDURES;

CREATE OR REPLACE TASK DEPARTMENT_WISE_SALES_KPI
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL DEPARTMENT_WISE_SALES_KPI();

SHOW TASKS;

ALTER TASK DEPARTMENT_WISE_SALES_KPI RESUME;
ALTER TASK DEPARTMENT_WISE_SALES_KPI SUSPEND;

SELECT * FROM RETAILS.PUBLIC.DEPARTMENT_WISE_SALES_KPI;


/*o D) Brand-wise sales: Calculate the sales value for each brand (in the Product table) to 
identify top-selling brands.*/
CREATE OR REPLACE PROCEDURE BRAND_WISE_SALES_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE BRAND_WISE_SALES_KPI AS
(SELECT P.BRAND,SUM(T.SALES_VALUE) AS TOTAL_AMOUNT 
FROM RETAILS.PUBLIC.PRODUCT_RAW P
LEFT JOIN RETAILS.PUBLIC.TRANSACTION_NEW T
ON P.PRODUCT_ID=T.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC);
$$;

CALL BRAND_WISE_SALES_KPI();

SHOW PROCEDURES;

CREATE OR REPLACE TASK BRAND_WISE_SALES_KPI
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL BRAND_WISE_SALES_KPI();

SHOW TASKS;

ALTER TASK BRAND_WISE_SALES_KPI RESUME;
ALTER TASK BRAND_WISE_SALES_KPI SUSPEND;

SELECT * FROM RETAILS.PUBLIC.DEPARTMENT_WISE_SALES_KPI;
-------------------------------------------------------------------------------------------------

/*5. Transaction KPIs: 
o A) Total sales value: Calculate the sum of sales values (in the Transaction_data table) 
to measure overall revenue. */

SELECT SUM(SALES_VALUE) AS TOTAL_AMOUNT FROM RETAILS.PUBLIC.TRANSACTION_NEW;

/*o B) Average transaction value: Calculate the average sales value per transaction to 
understand customer spending patterns. */

SELECT BASKET_ID, AVG(SALES_VALUE) AS AVG_AMOUNT 
FROM RETAILS.PUBLIC.TRANSACTION_NEW
GROUP BY 1
ORDER BY 2 DESC;

/* C) o Quantity sold: Measure the total quantity sold (in the Transaction_data table) to 
understand product demand. */

SELECT T.PRODUCT_ID, P.COMMODITY_DESC,COUNT(T.QUANTITY) AS TOTAL_AMOUNT
FROM RETAILS.PUBLIC.TRANSACTION_NEW T 
LEFT JOIN RETAILS.PUBLIC.PRODUCT_RAW P
ON T.PRODUCT_ID=P.PRODUCT_ID
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;

/*
o D) Discounts: Analyze the amount and impact of discounts (RETAIL_DISC, 
COUPON_DISC, COUPON_MATCH_DISC) on sales value.*/

SELECT * FROM RETAILS.PUBLIC.TRANSACTION_NEW;

SELECT RETAIL_DISC,COUPON_DISC,COUPON_DISC,SUM(SALES_VALUE) AS AMOUNT
FROM RETAILS.PUBLIC.TRANSACTION_NEW
GROUP BY 1,2,3
ORDER BY 4 DESC;
-------
CREATE OR REPLACE PROCEDURE DISCOUNT_IMPACT_ON_SALES_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE DISCOUNT_IMPACT_ON_SALES_KPI AS
(SELECT 
    P.DEPARTMENT,
    SUM(T.SALES_VALUE) AS Net_Revenue,
    SUM(ABS(T.RETAIL_DISC)) AS Total_Retail_Disc,
    SUM(ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)) AS Total_Coupon_Disc,
    SUM(T.SALES_VALUE + ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)) AS Gross_Revenue,
    ROUND(
        (SUM(ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)) * 100.0) / 
        NULLIF(SUM(T.SALES_VALUE + ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)), 0), 
    2) AS Discount_Impact_Pct
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
JOIN RETAILS.PUBLIC.PRODUCT_RAW P ON T.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1
ORDER BY Discount_Impact_Pct DESC);
$$;

CALL DISCOUNT_IMPACT_ON_SALES_KPI();

SHOW PROCEDURES;

CREATE OR REPLACE TASK DISCOUNT_IMPACT_ON_SALES_KPI
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL DISCOUNT_IMPACT_ON_SALES_KPI();

SHOW TASKS;

ALTER TASK DISCOUNT_IMPACT_ON_SALES_KPI RESUME;
ALTER TASK DISCOUNT_IMPACT_ON_SALES_KPI SUSPEND;

SELECT * FROM RETAILS.PUBLIC.DISCOUNT_IMPACT_ON_SALES_KPI;

-------------------------------------------------------------------------------------------------
/* DESCRIPTIVE ANALYSIS

o A) Explore demographic characteristics such as age distribution, marital 
status, income levels, homeownership, household composition, 
household size, and kid categories. */
CREATE OR REPLACE PROCEDURE DEMOGRAPHIC_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE DEMOGRAPHIC_KPI AS
(SELECT AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,
HOMEOWNER_DESC,HH_COMP_DESC,
HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,
COUNT(HOUSEHOLD_KEY) AS TOTAL_HOUSEHOLDS,
ROUND(COUNT(HOMEOWNER_DESC)*100 / SUM(COUNT(HOUSEHOLD_KEY)) OVER(),2) AS  TOTAL_PCT
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1,2,3,4,5,6,7
ORDER BY TOTAL_HOUSEHOLDS DESC);
$$;                                      -- INDICATES HOMEOWNER DO BULK PURCHASE 

CALL DEMOGRAPHIC_KPI();

/*o B) Analyze campaign descriptions and duration. */

SELECT DESCRIPTION,CAMPAIGN,
MAX(START_DAY) AS START_DAY,
MAX(END_DAY) AS END_DAY,
MAX(END_DAY)-MAX(START_DAY) AS CAMPAIGN_DURATION
FROM RETAILS.PUBLIC.CAMPAIGN_DESC_RAW
GROUP BY 1,2
ORDER BY CAMPAIGN_DURATION DESC;    -- CAMPAIGN NO 15 INVEST 161 DAYS FOR ITS BRAND AWARENESS AMONG PEOPLE


/*o C) Examine product details including manufacturer, department, brand, 
commodity description, sub-commodity description, and size.*/

SELECT DEPARTMENT,BRAND,
COMMODITY_DESC,
COUNT(DISTINCT PRODUCT_ID) AS SKU_Count,
COUNT(DISTINCT MANUFACTURER) AS Manufacturer_Count
FROM RETAILS.PUBLIC.PRODUCT_RAW
GROUP BY 1, 2, 3
ORDER BY SKU_Count DESC;

----CHECKING  WHICH AGE GROUP LIKE TO PURCHASE TYPE OF MORE ITEMS

CREATE OR REPLACE PROCEDURE SPENDING_KPI()
RETURNS STRING
LANGUAGE SQL AS
$$
CREATE OR REPLACE TABLE SPENDING_KPI AS
(SELECT D.AGE_DESC,P.DEPARTMENT,P.COMMODITY_DESC,
SUM(T.SALES_VALUE) AS TOTAL_AMOUNT,
COUNT(DISTINCT T.BASKET_ID) AS TOTAL_VISITS,
SUM(T.SALES_VALUE)/ NULLIF(COUNT(DISTINCT T.BASKET_ID),0)AS AVG_SPEND_PER_VISIT
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
JOIN RETAILS.PUBLIC.PRODUCT_RAW P ON T.PRODUCT_ID=P.PRODUCT_ID
JOIN RETAILS.PUBLIC.DEMOGRAPHIC_RAW D ON T.HOUSEHOLD_KEY=D.HOUSEHOLD_KEY
GROUP BY 1,2,3
ORDER BY 1,4 DESC);
$$;                           -- IN ALL AGE GROUP MAXIMUM REVENUE GENERATED FROM GROCCERY DEPARTMENT SOFT DRINKS COMMODITY

CALL SPENDING_KPI();

SHOW PROCEDURES;

CREATE OR REPLACE TASK SPENDING_KPI
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 20 * * 6 UTC'
AS CALL SPENDING_KPI();

SHOW TASKS;

ALTER TASK SPENDING_KPI RESUME;
ALTER TASK SPENDING_KPI SUSPEND;

SELECT * FROM RETAILS.PUBLIC.SPENDING_KPI;
---------------------------------------------------------------------------
/*2. Customer Segmentation: 
o A) Segment customers based on demographic attributes such as age, 
marital status, income, and household composition. */

SELECT AGE_DESC,INCOME_DESC,HH_COMP_DESC,
COUNT(HOUSEHOLD_KEY) AS SEGMENT_SIZE,
    CASE 
        WHEN INCOME_DESC IN ('100-124K', '125-149K', '150-174K', '175-199K', '200-249K', '250K+') THEN 'High Earners'
        WHEN HH_COMP_DESC = '2 Adults, No Kids' THEN 'Empty Nesters / DINKs'
        WHEN HH_COMP_DESC = '2 Adults, Kids' THEN 'Traditional Families'
        ELSE 'Other'
    END AS SEGMENT_LABEL
FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAW
GROUP BY 1, 2, 3
ORDER BY SEGMENT_SIZE DESC;

/*o B) Analyze customer behavior and preferences using transaction data.*/

SELECT T.HOUSEHOLD_KEY,
    COUNT(DISTINCT T.BASKET_ID) AS FREQUENCY,
    SUM(T.SALES_VALUE) AS TOTAL_REVENUE,
    ROUND(SUM(T.SALES_VALUE) / COUNT(DISTINCT T.BASKET_ID), 2) AS AVG_BASKET_VALUE,
    CASE 
        WHEN COUNT(DISTINCT T.BASKET_ID) > 50 THEN 'Loyalist'
        WHEN COUNT(DISTINCT T.BASKET_ID) BETWEEN 10 AND 50 THEN 'Regular'
        ELSE 'Occasional'
    END AS LOYALTY_TIE
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
GROUP BY T.HOUSEHOLD_KEY;

/*o C) Group customers based on their response to campaigns and coupon 
redemption. */

SELECT 
    T.household_key,
    SUM(ABS(T.COUPON_DISC)) AS Total_Coupon_Savings,
    COUNT(DISTINCT CRN.COUPON_UPC) AS Unique_Coupons_Redeemed,
    CASE 
        WHEN SUM(ABS(T.COUPON_DISC)) > 50 THEN 'Coupon Hunter'
        WHEN SUM(ABS(T.COUPON_DISC)) > 0 THEN 'Casual Saver'
        ELSE 'Full Price Buyer'
    END AS Savings_Profile
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
LEFT JOIN RETAILS.PUBLIC.COUPON_REDEMPT_NEW CRN ON T.household_key = CRN.household_key
GROUP BY T.household_key;
---------------------------------------------------------------------------------
/*4. Sales and Revenue Analysis: 
o Analyze transaction data to understand sales patterns, quantities, and 
sales values. */

SELECT 
    P.DEPARTMENT,
    SUM(T.QUANTITY) AS TOTAL_UNIT_SOLD,
    SUM(T.SALES_VALUE) AS TOTAL_REVENUE,
    ROUND(SUM(T.SALES_VALUE) / NULLIF(SUM(T.QUANTITY), 0), 2) AS AVG_UNIT_PRICE
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
JOIN RETAILS.PUBLIC.PRODUCT_RAW P ON T.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1
ORDER BY Total_Revenue DESC;

/*o Identify the top-selling products, brands, and departments. */

WITH BRAND_SALES AS (
    SELECT 
        P.DEPARTMENT,
        P.BRAND,
        SUM(T.SALES_VALUE) AS BRAND_REVENUE,
        RANK() OVER(PARTITION BY P.DEPARTMENT ORDER BY SUM(T.SALES_VALUE) DESC) as SALES_BANK
    FROM RETAILS.PUBLIC.TRANSACTION_NEW T
    JOIN RETAILS.PUBLIC.PRODUCT_RAW P ON T.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY 1, 2
)
SELECT * FROM BRAND_SALES 
WHERE SALES_BANK <= 5;     --- TOP 5 BRANDS IN EVERRY DEPARTMENT


/*o Explore the correlation between sales and discounts (retail discount, 
coupon discount, coupon match discount).*/

SELECT 
    P.COMMODITY_DESC,
    -- Calculate Total Discount across all types
    SUM(ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)) AS Total_Discount_Applied,
    SUM(T.SALES_VALUE) AS Total_Sales_Value,
    -- Measure the "Depth" of the discount
    ROUND(
        SUM(ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)) * 100.0 / 
        NULLIF(SUM(T.SALES_VALUE + ABS(T.RETAIL_DISC) + ABS(T.COUPON_DISC) + ABS(T.COUPON_MATCH_DISC)), 0), 
    2) AS Discount_Depth_Pct,
    -- Measure if depth leads to more units per basket
    ROUND(SUM(T.QUANTITY) * 1.0 / COUNT(DISTINCT T.BASKET_ID), 2) AS Avg_Units_Per_Basket
FROM RETAILS.PUBLIC.TRANSACTION_NEW T
JOIN RETAILS.PUBLIC.PRODUCT_RAW P ON T.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1
HAVING Total_Sales_Value > 100 -- Focus on products with meaningful data
ORDER BY Discount_Depth_Pct DESC;

----------------------------------------------------------------------------------------------------
-- UPSELLING OPPORTUNITY
SELECT 
    P1.COMMODITY_DESC AS Product_A, 
    P2.COMMODITY_DESC AS Product_B, 
    COUNT(*) AS Times_Bought_Together
FROM RETAILS.PUBLIC.TRANSACTION_NEW T1
JOIN RETAILS.PUBLIC.TRANSACTION_NEW T2 
    ON T1.BASKET_ID = T2.BASKET_ID AND T1.PRODUCT_ID < T2.PRODUCT_ID
JOIN RETAILS.PUBLIC.PRODUCT_RAW P1 ON T1.PRODUCT_ID = P1.PRODUCT_ID
JOIN RETAILS.PUBLIC.PRODUCT_RAW P2 ON T2.PRODUCT_ID = P2.PRODUCT_ID
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;
 
